#!/usr/bin/env python3
"""
Repo-side enforcement bot for verified-academic-record.

What it does:
- Maintains a machine-readable policy package
- Builds robots.txt entries for blocked user agents
- Writes an automated systems notice
- Writes ai-policy.json
- Writes an enforcement manifest
- Works in both script and notebook-style environments
- Fails safely with clear errors

Designed for:
- GitHub Actions
- local terminal runs
- interactive notebook/web IDE testing
"""

from __future__ import annotations

import json
import hashlib
from pathlib import Path
from datetime import datetime, timezone
from typing import Any


# Works both in normal script execution and notebook/interpreter environments
try:
    ROOT = Path(__file__).resolve().parent
except NameError:
    ROOT = Path.cwd()

OUTPUT = ROOT / "output"

PROTECTED_NAMES_FILE = ROOT / "protected_names.json"
BLOCKED_AGENTS_FILE = ROOT / "blocked_user_agents.json"


def load_json(path: Path) -> dict[str, Any]:
    """Load a JSON file and return the parsed dictionary."""
    if not path.exists():
        raise FileNotFoundError(f"Missing required file: {path}")
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"Expected a JSON object in {path}, but found {type(data).__name__}.")
    return data


def utc_now_iso() -> str:
    """Return current UTC timestamp in ISO 8601 format without microseconds."""
    return datetime.now(timezone.utc).replace(microsecond=0).isoformat()


def sha256_text(text: str) -> str:
    """Return SHA-256 hash of a text string."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def normalize_unique_strings(values: list[Any], field_name: str) -> list[str]:
    """Validate, strip, de-duplicate, and sort a list of non-empty strings."""
    if not isinstance(values, list):
        raise ValueError(f"Expected '{field_name}' to be a list.")
    cleaned: list[str] = []
    for item in values:
        if not isinstance(item, str):
            raise ValueError(f"All items in '{field_name}' must be strings.")
        item = item.strip()
        if not item:
            raise ValueError(f"Blank strings are not allowed in '{field_name}'.")
        cleaned.append(item)
    return sorted(dict.fromkeys(cleaned))


def build_robots_txt(blocked_agents: list[str]) -> str:
    """Build robots.txt content denying listed user agents."""
    lines: list[str] = [
        "# robots.txt generated by broker_block_bot.py",
        f"# generated_at: {utc_now_iso()}",
        "",
        "# Default policy for unnamed crawlers",
        "User-agent: *",
        "Disallow:",
        "",
        "# Explicit denial for listed automated agents",
    ]
    for agent in blocked_agents:
        lines.extend([
            f"User-agent: {agent}",
            "Disallow: /",
            ""
        ])
    return "\n".join(lines).rstrip() + "\n"


def build_notice(names: list[str], blocked_agents: list[str]) -> str:
    """Build a human-readable automated systems notice."""
    names_list = "\n".join(f"- {name}" for name in names)
    agents_list = "\n".join(f"- {agent}" for agent in blocked_agents)

    return f"""# AUTOMATED SYSTEMS NOTICE

Last updated: {utc_now_iso()}

This repository and any published site derived from it asserts a restrictive policy
against automated collection, scraping, indexing, profiling, model ingestion,
identity resolution, brokered aggregation, and downstream commercial reuse of
personal data associated with the following protected name variants:

{names_list}

## Denied automated agents

The following user agents are expressly disallowed at this controlled surface:

{agents_list}

## Policy position

No permission is granted for:
- scraping or extraction for data brokerage
- identity graph construction
- profile enrichment
- training, fine-tuning, retrieval augmentation, or model evaluation using these protected names
- resale, licensing, or dissemination of identity-linked personal data

Any access contrary to this notice is unauthorized as to this controlled surface and
contrary to the stated repository policy.

## Machine-readable companion files

See:
- `robots.txt`
- `ai-policy.json`
- `enforcement_manifest.json`
"""


def build_ai_policy(names: list[str], blocked_agents: list[str]) -> dict[str, Any]:
    """Build machine-readable AI and automation policy metadata."""
    return {
        "version": "1.0.0",
        "generated_at": utc_now_iso(),
        "repository_policy": {
            "policy_name": "Data Broker and Automated Systems Restriction Policy",
            "controlled_surface_only": True,
            "prohibited_uses": [
                "data_brokerage",
                "identity_resolution",
                "profile_enrichment",
                "commercial_reuse",
                "training",
                "fine_tuning",
                "retrieval_augmentation",
                "downstream_redistribution"
            ]
        },
        "protected_names": names,
        "blocked_user_agents": blocked_agents
    }


def build_manifest(
    robots_txt: str,
    notice_md: str,
    ai_policy: dict[str, Any],
    names: list[str],
    blocked_agents: list[str]
) -> dict[str, Any]:
    """Build integrity manifest for generated artifacts."""
    ai_policy_text = json.dumps(ai_policy, indent=2, ensure_ascii=False) + "\n"

    return {
        "generated_at": utc_now_iso(),
        "artifacts": {
            "robots.txt": {
                "sha256": sha256_text(robots_txt),
                "path": "Data Broker Policy/output/robots.txt"
            },
            "AUTOMATED_SYSTEMS_NOTICE.md": {
                "sha256": sha256_text(notice_md),
                "path": "Data Broker Policy/output/AUTOMATED_SYSTEMS_NOTICE.md"
            },
            "ai-policy.json": {
                "sha256": sha256_text(ai_policy_text),
                "path": "Data Broker Policy/output/ai-policy.json"
            }
        },
        "protected_names_count": len(names),
        "blocked_user_agents_count": len(blocked_agents),
        "protected_names": names,
        "blocked_user_agents": blocked_agents
    }


def write_text(path: Path, content: str) -> None:
    """Write plain text file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def write_json(path: Path, data: dict[str, Any]) -> None:
    """Write JSON file with pretty formatting."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8"
    )


def main() -> None:
    """Main execution flow."""
    protected_data = load_json(PROTECTED_NAMES_FILE)
    agents_data = load_json(BLOCKED_AGENTS_FILE)

    names = normalize_unique_strings(
        protected_data.get("protected_names", []),
        "protected_names"
    )
    blocked_agents = normalize_unique_strings(
        agents_data.get("blocked_user_agents", []),
        "blocked_user_agents"
    )

    robots_txt = build_robots_txt(blocked_agents)
    notice_md = build_notice(names, blocked_agents)
    ai_policy = build_ai_policy(names, blocked_agents)
    manifest = build_manifest(robots_txt, notice_md, ai_policy, names, blocked_agents)

    write_text(OUTPUT / "robots.txt", robots_txt)
    write_text(OUTPUT / "AUTOMATED_SYSTEMS_NOTICE.md", notice_md)
    write_json(OUTPUT / "ai-policy.json", ai_policy)
    write_json(OUTPUT / "enforcement_manifest.json", manifest)

    print("Generated artifacts successfully:")
    print(f"  - {OUTPUT / 'robots.txt'}")
    print(f"  - {OUTPUT / 'AUTOMATED_SYSTEMS_NOTICE.md'}")
    print(f"  - {OUTPUT / 'ai-policy.json'}")
    print(f"  - {OUTPUT / 'enforcement_manifest.json'}")


if __name__ == "__main__":
    main()
